-- CreateTable
CREATE TABLE "GymPlan" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "price" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "Feature" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "gymPlanId" INTEGER NOT NULL,
    CONSTRAINT "Feature_gymPlanId_fkey" FOREIGN KEY ("gymPlanId") REFERENCES "GymPlan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
